"""init models

Revision ID: f8f98cfc925e
Revises: 
Create Date: 2026-04-17 15:44:48.556296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8f98cfc925e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bang_gia',
    sa.Column('bangia_id', sa.Integer(), nullable=False),
    sa.Column('thang', sa.Integer(), nullable=False),
    sa.Column('nam', sa.Integer(), nullable=False),
    sa.Column('gia_phong_cap1', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('gia_phong_cap2', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('don_gia_dien', sa.Numeric(precision=10, scale=0), nullable=False),
    sa.Column('don_gia_nuoc', sa.Numeric(precision=10, scale=0), nullable=False),
    sa.Column('phi_wifi', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('phi_ve_sinh', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('phi_gui_xe', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('bangia_id'),
    sa.UniqueConstraint('thang', 'nam')
    )
    op.create_table('khach_thue',
    sa.Column('khach_id', sa.Integer(), nullable=False),
    sa.Column('ho_ten', sa.String(length=100), nullable=False),
    sa.Column('cccd', sa.String(length=20), nullable=True),
    sa.Column('ngay_sinh', sa.Date(), nullable=True),
    sa.Column('sdt', sa.String(length=15), nullable=True),
    sa.Column('dia_chi', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('la_chinh', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('khach_id'),
    sa.UniqueConstraint('cccd')
    )
    op.create_table('phong',
    sa.Column('phong_id', sa.Integer(), nullable=False),
    sa.Column('so_phong', sa.String(length=10), nullable=False),
    sa.Column('tang', sa.Integer(), nullable=True),
    sa.Column('dien_tich', sa.Float(), nullable=True),
    sa.Column('cap_phong', sa.String(length=10), nullable=True),
    sa.Column('trang_thai', sa.String(length=20), nullable=True),
    sa.Column('mo_ta', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('phong_id'),
    sa.UniqueConstraint('so_phong')
    )
    op.create_table('hop_dong',
    sa.Column('hopdong_id', sa.Integer(), nullable=False),
    sa.Column('phong_id', sa.Integer(), nullable=False),
    sa.Column('khach_id', sa.Integer(), nullable=False),
    sa.Column('ngay_bat_dau', sa.Date(), nullable=False),
    sa.Column('ngay_ket_thuc', sa.Date(), nullable=True),
    sa.Column('trang_thai', sa.String(length=20), nullable=True),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['khach_id'], ['khach_thue.khach_id'], ),
    sa.ForeignKeyConstraint(['phong_id'], ['phong.phong_id'], ),
    sa.PrimaryKeyConstraint('hopdong_id')
    )
    op.create_table('thanh_toan_thang',
    sa.Column('tt_id', sa.Integer(), nullable=False),
    sa.Column('hopdong_id', sa.Integer(), nullable=False),
    sa.Column('thang', sa.Integer(), nullable=False),
    sa.Column('nam', sa.Integer(), nullable=False),
    sa.Column('so_dien', sa.Float(), nullable=True),
    sa.Column('so_nuoc', sa.Float(), nullable=True),
    sa.Column('trang_thai', sa.String(length=20), nullable=True),
    sa.Column('ngay_thanh_toan', sa.Date(), nullable=True),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hopdong_id'], ['hop_dong.hopdong_id'], ),
    sa.PrimaryKeyConstraint('tt_id'),
    sa.UniqueConstraint('hopdong_id', 'thang', 'nam')
    )
    op.create_table('hoa_don',
    sa.Column('hoadon_id', sa.Integer(), nullable=False),
    sa.Column('tt_id', sa.Integer(), nullable=False),
    sa.Column('tien_phong', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('tien_dien', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('tien_nuoc', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('phi_dich_vu', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('tong_tien', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('ngay_tao', sa.Date(), nullable=True),
    sa.Column('snapshot_don_gia_dien', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('snapshot_don_gia_nuoc', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('snapshot_gia_phong', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.ForeignKeyConstraint(['tt_id'], ['thanh_toan_thang.tt_id'], ),
    sa.PrimaryKeyConstraint('hoadon_id'),
    sa.UniqueConstraint('tt_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hoa_don')
    op.drop_table('thanh_toan_thang')
    op.drop_table('hop_dong')
    op.drop_table('phong')
    op.drop_table('khach_thue')
    op.drop_table('bang_gia')
    # ### end Alembic commands ###
